language:
- node_js
- php
php:
- 7.1
install:
- npm install
script:
- composer install
cache:
  directories:
  - node_modules
  - vendor
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "main" ]; then ENVIRONMENT_NAME=production; fi
- vendor/bin/coveralls -v
- vendor/bin/phpcs -n --standard=PSR1,PSR2 src/
- vendor/bin/phpcbf src/
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $ENVIRONMENT_NAME"
env:
  global:
  - secure: WsqiVz6x1S9tKb2rMnr1T7xa/C54c4Nw1mI9ovdcYwmYeHAatuM1Wcur80byTlZSFof823R3N6ddYeAS4k0lF2tOg28HTOu4gCvPJ+QiBlNzo70E+cKlcKH2gBA+kWzXIqA9MA5qD4kqadLj2bbaAO6bFo1NVKpbNosRovB8o5jnVpZeyqiu4Z3FVVPclGC+1cTbgT4TRWee3BkkzhPR75sd/1Kj4s9yQS3QlTHKgYKNvjaOjrcKNnjyn4eQyVEjDZ2c9xmltpk6TXrM+fRrk9amv66bRPzOfNwSrhb/9px4f5QksiNyb52NHdavdDHQBL3LwIkkvoTwjHCpn43bMABTEn/WzMNA2LgDrTXfm92fM5wOk3yS6JouhrdBXERtufcl6lnbNjdcRBY0Jca711IDdjoVwP5I9RXHydv+zHK6ds0ielrV4+Xrjm66xcYQUiJR6sak59ANT9AP69RHGAwpsC+p57JQ92g5lfN6vyFbENwRrNMR7Dh9AsoZUHcSGoTO/REQaWcjuZGRHbasaykLsY1SWcAGthDjieCJC6R3scigOTp4cLKDK6tYazhepni1JWm7qrRXZSRWViW7ENSH6E1UP1eUSqdKb9iGrxFMW6pR7fzzpop0OkUOxPUTB/Ptt5SRf53GMzzRklwsqdBZHikPxeQYse/pOFmPCeY=
  - secure: o6mR2iOr6ydCRwMI6Ig3wNKt95VYrh8UdHsmorYxBEoHQgGQYrawagycHr8q6cLoNFTzZTE0phZ2M459akhwh4fHyQg0UuZApMEccwdxC14ZQ/H2JIu2/Ay7TQvpCpm8zEtVukxqaSryxtXbITKBpgN5M/XNCj19w4ASR1JMWvmABgVDvSbzEEgbR2s1VCAYAoa5zU/uRXBWwX1emOQ/cYWGCbgmNlVqthkxPaVVWtudlsVy6l52bFwPxA7H7BJeCD5v+zjQnteBKPvAB7O5Ece0M2l95uFjZiShdCUwtuXisrOAm3RVcPHeyvcXrJG0ldQlEk8PKq9exmcYL9vUH2VsTIlHSj2nghiI7sF6rKtV+zrl2AWv6dbnUNctre7PGYzV40LZi0JmTyVKUmjGmZPppPvFyHfF2mhEBR5vSm4zJRM8fCChJl2JGFeh/LyKLV3XCaDiyWnpEtRIB6ne762URMCuwq+UUpHhiCqQDO2nVGsMzHkHtfk+dAHO7ICgWyqAqUNn6icXy3wGxcnJAK/ieQglrzWjgSFGCCGDqRzwpcE3z2HxBd5VLlisPF9EXLbNYutNYmcZyTwidd1AZiL0OZBDjGglmf72N7HTAsg7miTda4vKb+jCovWsYvaZ2QCg1uNRx7QvrPoPEmxocAElHKNzeJNN6R5KKAr2qMY=
